source 'http://rubygems.org'
ruby "2.2.0"

gem 'feedjira', '~> 1.6.0'
gem 'streamworker', '~> 0.0', git: 'https://github.com/rranshous/streamworker.git'
gem 'persistent_httparty'
gem 'pry', group: :development
