#!ruby

script_types = %w(worker webapp)

File.open('./Procfile', 'w') do |fh|
  script_types.each do |type|
    fh.puts
    file_name = "#{type}.rb"
    fh.puts "# #{type}"
    Dir["**/#{file_name}"].map do |path|
      app_dir_path = File.dirname(path)
      app_name = app_dir_path.split('/').join('_')
      fh.puts "#{app_name}: sh -c '#{app_dir_path} && bundle exec ruby #{file_name}'"
    end
  end
end
